apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-app
  namespace: dev-prestashop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-new-app
  template:
    metadata:
      labels:
        app: my-new-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: my-new-app
        image: nginx:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-new-app
  namespace: dev-prestashop
spec:
  selector:
    app: my-new-app
  ports:
  - port: 8080
    targetPort: 8080