apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: dev-monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
    - name: Mimir
      type: prometheus
      access: proxy
      url: http://mimir:8080/prometheus
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3200