# Grafana - Visualization
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: dev-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
---
# Loki - Logs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: dev-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        ports:
        - containerPort: 3100
---
# Mimir - Metrics
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: dev-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:latest
        ports:
        - containerPort: 8080
---
# Tempo - Traces
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: dev-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        ports:
        - containerPort: 3200
        args:
        - "-config.file=/etc/tempo.yaml"
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo.yaml
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap:
          name: tempo-config
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: dev-monitoring
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: dev-monitoring
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: dev-monitoring
spec:
  selector:
    app: mimir
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: dev-monitoring
spec:
  selector:
    app: tempo
  ports:
  - port: 3200
    targetPort: 3200