apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: dev-monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces